# Before running drop-fuzz copy this file to config.yml and modify settings.
# $ cp default.config.yml config.yml

# Drupal localhost URL
target_url: 'http://127.0.0.1/drupal'

# Path to contrib modules
module_path: '/var/www/html/drupal/modules/contrib'

# Optional 
drupal_username: 
drupal_password:
zap_apikey: 
