# drop-fuzz -- config.yml
# =========================
# To use, uncomment the below line(s) you find necessary, and replace
# the given values with your own.
#--------------------------------------------------------------------

drupal-url: 'http://127.0.0.1/drupal'
system-path: '/var/www/html/drupal'
#drupal-username: brian
#drupal-password: paranoid4ndr0id
#zap-apikey: abcdefghijk1234567
