# Before running drop-fuzz copy this file to config.yml and modify settings.
# $ cp default.config.yml config.yml

# Drupal localhost URL
drupal-url: 'http://127.0.0.1/drupal'
# Path to contrib modules
system-path: '/var/www/html/drupal/modules/contrib'
#drupal-username: brian
#drupal-password: paranoid4ndr0id
#zap-apikey: abcdefghijk1234567
